name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "c37989a5-c102-4d7b-abd3-5828ea0c6d38"
database_name = "memos-notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "memos-notes-kv"
preview_id = "4b1f2479900a44e7a4b5d437ab4d1a22"

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "memos-notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
