name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "2279b38a-2081-4c83-93de-42af0164bee9"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "notes-kv"
preview_id = "58604b634748432795438684ad39e5d8"

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
